version: "3"
services:
  server:
    build: ./server
    command: "bundle exec rails server -b 0.0.0.0"
    volumes:
      - ./server:/myapp/server
    ports:
      - "${SERVER_PORT}:3000"
    environment:
      - DATABASE_URL=postgres://postgres:servers@db:5432/servers
    depends_on:
      - db
  db:
    image: "postgres:alpine"
    ports:
      - "5432:5432"
    volumes:
      - server_db:/var/lib/postgresql/data
  client:
    build: ./client
    command: "npm run start"
    volumes:
      - ./client:/myapp/client
    ports:
      - "${CLIENT_PORT}:3000"
volumes:
  server_db:
